name: Deployments
description: Automated continuous deployment and delivery.
url: https://github.com/ploys/deployments
public: false

default_events:
- installation
- installation_repositories
- pull_request
- push

default_permissions:
  checks: write
  contents: read
  metadata: read
  pull_requests: read
