name: Deployments
description: Automated continuous deployment and delivery.
url: https://github.com/ploys/deployments
public: false

default_events:
- check_run
- check_suite
- installation
- installation_repositories
- pull_request
- push
- repository_dispatch

default_permissions:
  actions: read
  deployments: write
  checks: write
  contents: write
  metadata: read
  pull_requests: read
