name: Deployments
description: Automated continuous deployment and delivery.
url: https://github.com/ploys/deployments
public: false

default_events:
- installation
- installation_repositories
- push

default_permissions:
  checks: write
  metadata: read
