name: CI
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org

    - name: Install Package
      run: yarn install

    - name: Lint Package
      run: yarn run lint

    - name: Publish Packages
      run: npx lerna publish from-package --yes --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://npm.pkg.github.com

    - name: Install Package
      run: yarn install

    - name: Test Package
      run: yarn run test

    - name: Publish Packages
      run: npx lerna publish from-package --yes --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
